/** Embedded candidate profile — keep in sync with assistant prompt */
const RESUME = {
  name: "Subodh Raghunath Patil",
  title: "Senior Frontend Engineer | Angular | AI-Powered Applications",
  location: "Pune, India",
  phone: "+91-8149488965",
  email: "subodhpatil10@gmail.com",
  linkedin: "https://www.linkedin.com/in/subodh-patil-56b691196",
  experienceYears: "8+",

  skills: [
    { name: "Angular", aliases: ["angular", "angularjs", "angular 2", "angular 17"] },
    { name: "TypeScript", aliases: ["typescript", "ts"] },
    { name: "JavaScript", aliases: ["javascript", "es6", "es6+", "js"] },
    { name: "HTML5", aliases: ["html", "html5"] },
    { name: "CSS3", aliases: ["css", "css3"] },
    { name: "SCSS", aliases: ["scss", "sass"] },
    { name: "RxJS", aliases: ["rxjs", "reactive"] },
    { name: "NgRx", aliases: ["ngrx", "state management"] },
    { name: "REST APIs", aliases: ["rest", "rest api", "restful"] },
    { name: "OpenAI API", aliases: ["openai", "llm", "gpt"] },
    { name: "Responsive Design", aliases: ["responsive", "mobile-first"] },
    { name: "Accessibility", aliases: ["accessibility", "a11y", "wcag"] },
    { name: "Performance Optimization", aliases: ["performance", "lazy loading", "onpush", "bundle"] },
    { name: "Git", aliases: ["git", "version control"] },
    { name: "Agile/Scrum", aliases: ["agile", "scrum"] },
    { name: "Chrome DevTools", aliases: ["devtools", "chrome devtools"] },
    { name: "Bootstrap", aliases: ["bootstrap", "bootstrap 5"] },
    { name: "Angular Material", aliases: ["angular material", "material"] },
    { name: "PrimeNG", aliases: ["primeng"] },
    { name: "Webpack", aliases: ["webpack"] },
    { name: "Angular CLI", aliases: ["angular cli", "ng cli"] },
    { name: "CI/CD", aliases: ["ci/cd", "cicd", "continuous integration"] },
    { name: "Jasmine/Karma", aliases: ["jasmine", "karma", "unit test", "unit testing"] },
    { name: "Jest", aliases: ["jest"] },
    { name: "Node.js", aliases: ["node", "node.js", "nodejs"] },
    { name: "Postman", aliases: ["postman"] },
    { name: "Component-Driven Architecture", aliases: ["component-driven", "design system", "reusable component"] },
    { name: "Micro-Frontend", aliases: ["micro-frontend", "micro frontend", "module federation"] },
    { name: "Prompt Engineering", aliases: ["prompt engineering"] },
    { name: "AI Chatbots", aliases: ["chatbot", "chatbots"] },
  ],

  /** Skills we track as gaps when JD asks for them */
  jdWatchlist: [
    { name: "React", aliases: ["react", "react.js", "reactjs"], has: false },
    { name: "Vue.js", aliases: ["vue", "vue.js", "vuejs"], has: false },
    { name: "Next.js", aliases: ["next.js", "nextjs"], has: false },
    { name: "Redux", aliases: ["redux"], has: false },
    { name: "GraphQL", aliases: ["graphql"], has: false },
    { name: "Playwright", aliases: ["playwright"], has: false },
    { name: "Cypress", aliases: ["cypress", "e2e"], has: "partial" },
    { name: "Selenium", aliases: ["selenium"], has: false },
    { name: "Docker", aliases: ["docker"], has: false },
    { name: "AWS", aliases: ["aws", "amazon web services"], has: false },
    { name: "Azure", aliases: ["azure"], has: false },
    { name: "Kubernetes", aliases: ["kubernetes", "k8s"], has: false },
    { name: "Python", aliases: ["python"], has: false },
    { name: "Java", aliases: ["java"], has: false },
    { name: "C#", aliases: ["c#", ".net"], has: false },
    { name: "PHP", aliases: ["php", "cakephp"], has: false },
    { name: "MySQL", aliases: ["mysql"], has: false },
    { name: "MongoDB", aliases: ["mongodb"], has: false },
    { name: "Figma", aliases: ["figma"], has: "partial" },
  ],

  projects: [
    {
      name: "AI Smart Assistant Dashboard",
      stack: "Angular, OpenAI API, RxJS, NgRx",
      desc: "chatbot UX, smart search, workflow automation",
    },
    {
      name: "QuestNet BI Platform",
      stack: "Angular, dashboards",
      desc: "enterprise reporting, real-time data visualizations",
    },
    {
      name: "UBO Compliance Platform",
      stack: "Angular, NgRx",
      desc: "role-based UI, complex state, workflow modules",
    },
  ],
};
